# Generated by Django 4.0.4 on 2022-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_num', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('dong', models.TextField(blank=True, null=True)),
                ('sort_x', models.TextField(blank=True, null=True)),
                ('menu_x', models.TextField(blank=True, null=True)),
                ('naver_review_list', models.TextField(blank=True, null=True)),
                ('img_food', models.TextField(blank=True, null=True)),
                ('img_inner', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sort_y', models.TextField(blank=True, null=True)),
                ('kakao_review_list', models.TextField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('total_review_count', models.BigIntegerField(blank=True, null=True)),
                ('clustering', models.BigIntegerField(blank=True, null=True)),
                ('pos_rev_rate', models.FloatField(blank=True, db_column='pos_rev_Rate', null=True)),
            ],
        ),
    ]
