# Generated by Django 4.0.4 on 2022-05-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demo',
            table='demo',
        ),
    ]
