# Generated by Django 4.0.4 on 2022-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_demo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('sort_x', models.TextField(blank=True, null=True)),
                ('menu_x', models.TextField(blank=True, null=True)),
                ('naver_review_list', models.TextField(blank=True, null=True)),
                ('img_food', models.TextField(blank=True, null=True)),
                ('img_inner', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sort_y', models.TextField(blank=True, null=True)),
                ('kakao_review_list', models.TextField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('total_review_count', models.BigIntegerField(blank=True, null=True)),
                ('category', models.BigIntegerField(blank=True, null=True)),
                ('cluster', models.BigIntegerField(blank=True, null=True)),
                ('review_score', models.FloatField(blank=True, null=True)),
                ('region_code', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('sort_x', models.TextField(blank=True, null=True)),
                ('menu_x', models.TextField(blank=True, null=True)),
                ('naver_review_list', models.TextField(blank=True, null=True)),
                ('img_food', models.TextField(blank=True, null=True)),
                ('img_inner', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sort_y', models.TextField(blank=True, null=True)),
                ('kakao_review_list', models.TextField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('total_review_count', models.BigIntegerField(blank=True, null=True)),
                ('category', models.BigIntegerField(blank=True, null=True)),
                ('cluster', models.BigIntegerField(blank=True, null=True)),
                ('review_score', models.FloatField(blank=True, null=True)),
                ('region_code', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='MainDemo',
        ),
    ]
